version: '2.2'
services:

  django:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - /backup:/backup
  geoserver:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - geoserver-data-dir:/geoserver_data/data   
      - /backup:/backup
